apiVersion: v1
kind: Service
metadata:
  name: c3-express
  namespace: c3-express
spec:
  type: ClusterIP
  selector:
    app: c3-express
  ports:
    - name: http
      port: 80
      targetPort: 3000


