apiVersion: v1
kind: ConfigMap
metadata:
  name: webadmin-config
  namespace: webadmin
data:
  APP_ENV: "prod"
  PORT: "80"
  PUBLIC_HOST: "https://websiteadmin.appwallah.com"
  VENDURE_HOST: "https://websiteadmin.appwallah.com"
  VENDURE_PORT: "443"
  DB_HOST: "postgres.default.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "vendure6"
  DB_SCHEMA: "public"
  # Set to empty to disable MinIO/S3 storage and use local PV
  MINIO_ACCESS_KEY: e63cb0d336dd5ddf3fdabbca1fd5c0c0
  MINIO_SECRET_KEY: 93d22b03f01f65f8d60687f7f4f6e9532319a14a859c0aa352de8e24138dcab2
  MINIO_ENDPOINT: https://6e7f84c647e98d7c1c52ff4030406837.r2.cloudflarestorage.com
  GOOGLE_CLIENT_ID: "316619186166-l2kn79v617jpmefbqn36s15qh2s1lube.apps.googleusercontent.com"
  EASEBUZZ_CALLBACK_BASE_URL: "https://websiteadmin.appwallah.com"

