apiVersion: v1
kind: Service
metadata:
  name: webadmin
  namespace: webadmin
spec:
  type: ClusterIP
  selector:
    app: webadmin-server
  ports:
    - name: http
      port: 80
      targetPort: 80

