apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prepwise-storefront
  namespace: prepwise-storefront
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/server-snippet: |
      location ~ /.well-known/acme-challenge/ {
        return 200;
      }
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - prepwise.appwallah.com
        - prepwize.in
      secretName: prepwise-tls
  rules:
    - host: prepwise.appwallah.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prepwise-storefront
                port:
                  number: 80
    - host: prepwize.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prepwise-storefront
                port:
                  number: 80



