apiVersion: v1
kind: Service
metadata:
  name: prepwise-storefront
  namespace: prepwise-storefront
spec:
  type: ClusterIP
  selector:
    app: prepwise-storefront
  ports:
    - name: http
      port: 80
      targetPort: 8080



