apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storefrontstage
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.example.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml


